import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    colors: {
      'bg-app':      'var(--bg-app)',
      'bg-panel':    'var(--bg-panel)',
      'bg-raised':   'var(--bg-raised)',
      'bg-hover':    'var(--bg-hover)',
      'bg-selected': 'var(--bg-selected)',
      'border-default': 'var(--border-default)',
      'border-strong':  'var(--border-strong)',
      'text-primary':   'var(--text-primary)',
      'text-emphasis':  'var(--text-emphasis)',
      'text-secondary': 'var(--text-secondary)',
      'text-disabled':  'var(--text-disabled)',
      'text-accent':    'var(--text-accent)',
      'text-gain':      'var(--text-gain)',
      'text-loss':      'var(--text-loss)',
      'focus-ring': 'var(--focus-ring)',
      'ic-noise':  'var(--ic-noise)',
      'ic-weak':   'var(--ic-weak)',
      'ic-strong': 'var(--ic-strong)',
      'info': 'var(--info-500)',
      'warn': 'var(--warn-500)',
      'crit': 'var(--crit-500)',
      'ok':   'var(--ok-500)',
      'gain':      'var(--gain-500)',
      'gain-fill': 'var(--gain-900a)',
      'loss':      'var(--loss-500)',
      'loss-fill': 'var(--loss-900a)',
      'accent':        'var(--amber-500)',
      'accent-hover':  'var(--amber-600)',
      'accent-subtle': 'var(--amber-300)',
      'accent-fill':   'var(--amber-900a)',
      // ── shadcn compatibility aliases ──────────────────────────────────────
      // Maps shadcn class names (bg-background, text-foreground, etc.) to our
      // design tokens. Only src/ui/ (shadcn-generated files) uses these names.
      // All authored components use our semantic token classes exclusively.
      'background':             'var(--bg-app)',
      'foreground':             'var(--text-primary)',
      'card':                   'var(--bg-panel)',
      'card-foreground':        'var(--text-primary)',
      'popover':                'var(--bg-raised)',
      'popover-foreground':     'var(--text-primary)',
      'primary':                'var(--amber-500)',
      'primary-foreground':     'var(--gray-950)',
      'secondary':              'var(--bg-raised)',
      'secondary-foreground':   'var(--text-primary)',
      'muted':                  'var(--bg-raised)',
      'muted-foreground':       'var(--text-secondary)',
      'accent-compat':          'var(--bg-hover)',
      'accent-foreground':      'var(--text-primary)',
      'destructive':            'var(--loss-500)',
      'destructive-foreground': 'var(--gray-050)',
      'border':                 'var(--border-default)',
      'input':                  'var(--border-strong)',
      'ring':                   'var(--focus-ring)',
      // ──────────────────────────────────────────────────────────────────────
      white: '#ffffff',
      transparent: 'transparent',
      current: 'currentColor',
    },
    fontFamily: {
      ui:   ['Inter', 'system-ui', 'sans-serif'],
      mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
    },
    fontSize: {
      xs:          ['11px',   { lineHeight: '16px' }],
      sm:          ['12.5px', { lineHeight: '18px' }],
      md:          ['14px',   { lineHeight: '20px' }],
      base:        ['14px',   { lineHeight: '20px' }],
      lg:          ['16px',   { lineHeight: '24px' }],
      xl:          ['20px',   { lineHeight: '28px' }],
      metric:      ['22px',   { lineHeight: '28px', fontWeight: '500' }],
      'metric-lg': ['32px',   { lineHeight: '36px', fontWeight: '500' }],
    },
    spacing: {
      px:   '1px',
      '0':  '0',
      '1':  'var(--space-1)',
      '2':  'var(--space-2)',
      '3':  'var(--space-3)',
      '4':  'var(--space-4)',
      '5':  'var(--space-5)',
      '6':  'var(--space-6)',
      '7':  'var(--space-7)',
      '8':  'var(--space-8)',
      '9':  'var(--space-9)',
      '10': 'var(--space-10)',
    },
    borderRadius: {
      none: '0',
      sm:   'var(--radius-sm)',
      md:   'var(--radius-md)',
      lg:   'var(--radius-lg)',
      full: 'var(--radius-full)',
      DEFAULT: 'var(--radius-md)',
    },
    transitionDuration: {
      fast: 'var(--dur-fast)',
      base: 'var(--dur-base)',
      DEFAULT: 'var(--dur-base)',
    },
    transitionTimingFunction: {
      DEFAULT: 'var(--ease-standard)',
    },
  },
  plugins: [],
}

export default config
